# SPDX-License-Identifier: MIT
# Copyright (C) 2025-2026 Advanced Micro Devices, Inc.

name: Doxygen Documentation
on:
  push:
    branches:
      - main
permissions:
  contents: write  # Grant write permissions to allow pushing to gh-pages
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install -y graphviz texlive-latex-recommended pdf2svg
      - name: Download Doxygen release
        run: curl -L https://github.com/doxygen/doxygen/releases/download/Release_1_15_0/doxygen-1.15.0.linux.bin.tar.gz -o - | tar -C ${{github.workspace}} -xzf -
      - name: Generate Documentation
        run: |
            pushd doc
            ${{github.workspace}}/doxygen-1.15.0/bin/doxygen aie_api.doxygen
            popd
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/aie_api_output/html
 
